### ISSUE TITLE
Only python3 wheel built

### ISSUE THREAD

**Issue by Code0x58** [ktosiek/pytest-freezegun#11]
Thanks for releasing 0.3.0 to get #5 out!

I was expecting to see a `pytest_freezegun-0.3.0-py2.py3-none-any.whl` on [pypi](https://pypi.org/simple/pytest-freezegun/), but there's only a py2 version (e.g. [package](https://pypi.org/simple/python-stripzip/) with a [universal](https://wheel.readthedocs.io/en/stable/user_guide.html) wheel).

It doesn't look like requirements haven't changed, and the trove classifiers are still the same since 0.2.0, so I'm thinking this was an oversight. If it is the case, I'd be happy to help in whatever way I can.

_p.s. be careful not to re-upload the py3 0.3.0 package, otherwise the hash will change (thanks zip timestamps) and it will break people's lockfiles (e.g. for Pipenv or poetry). I'd recommend a new 0.3.1 release to be safe_

**Comment by ktosiek** [comment]
Thank you for the pointers. I'll try to make a universal wheel (and an sdist wouldn't hurt too). Do you think uploading it as 0.3.0.post1 (as in https://www.python.org/dev/peps/pep-0440/#post-releases) would make sense? I'm not really changing the software, so I feel a patch release declares a change that isn't really there.

**Comment by Code0x58** [comment]
Good points! 0.3.0.post1 makes sense to me and sounds good. I'm sure someone somewhere will appreciate an sdist

**Comment by ktosiek** [comment]
0.3.0.post1 is out. Please close this issue if it works for you on py2.

**Comment by Code0x58** [comment]
I can see the packages, and can confirm it fixes the python 2 issue. Thanks!
