### ISSUE TITLE
move_by freezer method

### ISSUE THREAD

**Issue by jasonkuhrt** [ktosiek/pytest-freezegun#12]
We currently have `freezer.move_to`. It would be nice if we could advance time by a relative increment.

Example:

```py
freezer.move_by('2 hours')
```

**Comment by ktosiek** [comment]
I think you can already do that with `freezer.tick(timedelta(hours=2))`, see https://github.com/spulec/freezegun#manual-ticks.

**Comment by jasonkuhrt** [comment]
Nice thanks!
