### ISSUE TITLE
Please "register" the "freeze_time" mark with pytest

### ISSUE THREAD

**Issue by dimaqq** [ktosiek/pytest-freezegun#13]
`pytest` says:

> site-packages/_pytest/mark/structures.py:324: PytestUnknownMarkWarning: Unknown pytest.mark.freeze_time - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
> PytestUnknownMarkWarning,

**Comment by retr0h** [comment]
Can we get this issue fixed?

**Comment by juanifioren** [comment]
@dimaqq Meanwhile I think doing this change you can remove the warning. Change:
```
@pytest.mark.freeze_time('2017-05-10')
def test_something(now, freezer):
    # code ...
    freezer.move_to('2017-06-10')  # One month later!.
    # code ...
```
to:
```
def test_something(now, freezer):
    freezer.move_to('2017-05-10')  # Today!
    # code ...
    freezer.move_to('2017-06-10')  # One month later!.
    # code ...
```
