### ISSUE TITLE
Duration fix breaks time

### ISSUE THREAD

**Issue by radiac** [ktosiek/pytest-freezegun#18]
The duration fix:

    ignore.append('_pytest')

seems to prevent freezegun from freezing `time` when a marker is set. 

I've added some tests to demonstrate this here:

https://github.com/radiac/pytest-freezegun/commit/fec97f71716dd8042af2d53e61a311142b617d75

**Comment by ktosiek** [comment]
Thank you for the tests, this seems to be the same problem as #6. I'll try to apply the fix from https://github.com/spulec/freezegun/issues/269#issuecomment-430939504 and check if it helps.

**Comment by ktosiek** [comment]
The fix should be in the 0.4.1 release.
