### ISSUE TITLE
0.4.1 Release does not freeze time in fixtures

### ISSUE THREAD

**Issue by chgad** [ktosiek/pytest-freezegun#24]
Hello, i just recognized that the latest release 0.4.1 does not freeze the time during fixture creation.

I'm running tests for django and have the following versions installed:

pytest == 5.2.2
pytest-freezegun == 0.4.1
freezegun == 0.3.15

which satisfies everything specified in [setup.cfg](https://github.com/ktosiek/pytest-freezegun/blob/master/setup.cfg#L32).

Freezing the time via the `freezer`fixture during the test works all fine.
I allready tried rolling back the versions for  pytest and freezegun but apperently none of the previous versions worked. However the prior release of pytest-freezegun `0.3.0.post1` works fine.

**Comment by chgad** [comment]
Maybe it is helpful if I roughly specify what I'm doing in the Test...

    @pytest.mark.freeze_time("2019-01-10 00:05:00")
    @pytest.mark.django_db
    def test_update_somefield(model_instance_fixture, freezer, ...):
        # I expect the value to be model_instance_fixture.modified == 2019-01-10 00:05:00+00:00 at this stage
        
        freezer.move_to("2019-01-10 00:07:00")
        # ... do some modifiaction on the model entry created by the fixture
        modified_model_instance = Model.objects.get(...) # 
        assert modified_model_instance.modified > model_instance_fixture.modified

The assert fails stating that modified_model_instance.modified has the value of `now` (Date/Time of test start.)

**Comment by ktosiek** [comment]
Are you using `auto_now` and calling `model_instance_fixture.save()`? `save()` will override the modification date just before writing the model to the database.

Which means your original version will get the new timestamp.

**Comment by chgad** [comment]
> Are you using auto_now and calling model_instance_fixture.save()?

Yes i do actually update the model instance. But why does this only happen with the new release and everything is fine in `0.3.0.post1`?

**Comment by ktosiek** [comment]
That's interesting. Is pytest-freezegun the only thing you've updated?

**Comment by chgad** [comment]
Well due to a horrible setup, which i just recognized now, there could be other packages that were also updated by mistake. None the less only switching versions of `pytest-freezegun` would do the trick. I will experiment a bit more with the other packages today.

**Comment by chgad** [comment]
So i did some research and it appears that no other "unpinned" package should hav an influence of any kind. However i also double checked that this is not a problem of being a Classbased test - even defining the method as function doesn't solve the issue.

However i need to state that the decorateor `@pytest.mark.freeze_time("2019-01-10 00:05:00")` and the time (found out by printing datetiem.now()) is also moved to the desired timestamp.

But the question remains: Why does the latest release break the django timestamps.

**Comment by ktosiek** [comment]
I think I've finally reproduced your issue, it will be fixed in 0.4.2.

**Comment by chgad** [comment]
Yea! It really fixed the issue. Thanks for looking into this!
