### ISSUE TITLE
pytest.mark.freeze_time does not work anymore with freezegun 0.3.11

### ISSUE THREAD

**Issue by bdauvergne** [ktosiek/pytest-freezegun#6]
See https://github.com/spulec/freezegun/issues/269

**Comment by ktosiek** [comment]
Thank you for the heads-up!
It seems to work for me, and I think CI should've catched that too. What version of pytest are you using?

**Comment by bdauvergne** [comment]
I signaled it to the freezegun project (https://github.com/spulec/freezegun/issues/269), they chose to add pytest to their whitelist (https://github.com/spulec/freezegun/commit/028dee229f06d200d0f79a130deaad65b14779ef) as they now use inspect.getstackframes() to choose which call to the time functions to intercept. It fixed the problem for now, but the way freeze_time works is problematic I think (it covers all calls around the test not only the test stackframe).

**Comment by ktosiek** [comment]
Hi! I'm closing the issue, as you've said it works now.

The `freeze_time` marker is supposed to freeze time for fixtures too, that's why it freezes a lot outside the test itself.

**Comment by bdauvergne** [comment]
I stopped using the freeze_time marker as it's unusable for me, I only use the freezer fixture now.
