### ISSUE TITLE
pytest4.0 released and pytest-freezegun can't work.

### ISSUE THREAD

**Issue by aodag** [ktosiek/pytest-freezegun#7]
would you release version that fixed to use markinfo?

**Comment by craiga** [comment]
For the benefit of anyone else thinking about submitting a PR to fix this, [it's already been done](https://github.com/ktosiek/pytest-freezegun/pull/5).

**Comment by ktosiek** [comment]
Should be available now! I was hoping to get more information on https://github.com/ktosiek/pytest-freezegun/issues/6 before doing a release, but I can always make another release later :-)
